### ISSUE TITLE
Hide Tab bar when scrolling

### ISSUE THREAD

**Issue by Brawl345** [anthonycr/Thunder-Browser#4]
I REALLY love this browser! Would it be possible to hide the tab bar when you are scrolling, like in Chrome, etc.? Thank you.

**Comment by anthonycr** [comment]
Hi @Brawl345 you can already do this by going into settings and turning on "Full-screen mode". If this doesn't work then please open another issue about it. Thanks, and enjoy :)

**Comment by Brawl345** [comment]
OH! Found it! Thank you!
